datasets: ["aids", "breast_cancer","gbsg", "metabric", "pbc", "tcga_brca", "veterans", "whas"] 
models: ["converse_single", "converse_siamese"]
seed: 42
n_bootstrap_iters: 20
val_size: 0.2
test_size: 0.2
event_col: "event"
time_col: "time"
interpolation: "linear"

# === Optuna Configuration ===
n_trials: 300
n_startup_trials: 30
optimization_metrics: ["cindex", "ibs"]
pruning: true

# === Utilities ===
n_jobs: -1
space_dir: "spaces"
output: "results_{dataset}_{time}.csv"
log_level: "INFO"
save_final_model: false
